<a href="https://colab.research.google.com/github/shashankmishra7-max/Pandas_project/blob/main/pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/subs.csv")
df.head()
df.max()

Subscribers gained    396
dtype: int64

In [3]:
df.sample(5)
df.value_counts()

Subscribers gained
105                   9
108                   6
88                    5
72                    5
123                   5
                     ..
295                   1
301                   1
306                   1
312                   1
396                   1
Name: count, Length: 180, dtype: int64

In [4]:
df.count()

Subscribers gained    365
dtype: int64

In [5]:
df.sum()
df.mean()
df.mode()
df.median()
df.var()
df.std()

Subscribers gained    62.675023
dtype: float64

In [6]:
df.describe()

       Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000

In [7]:
df[5:11]

    Subscribers gained
5                   46
6                   33
7                   40
8                   44
9                   74
10                  49

In [8]:
df[2::5]

     Subscribers gained
2                    40
7                    40
12                   49
17                   51
22                   50
..                  ...
342                 185
347                 212
352                 196
357                 177
362                 155

[73 rows x 1 columns]

In [9]:
df[2] = 50
df

     Subscribers gained   2
0                    48  50
1                    57  50
2                    40  50
3                    43  50
4                    44  50
..                  ...  ..
360                 231  50
361                 226  50
362                 155  50
363                 144  50
364                 172  50

[365 rows x 2 columns]

In [10]:
df[2:5] = [100,100]
df

     Subscribers gained    2
0                    48   50
1                    57   50
2                   100  100
3                   100  100
4                   100  100
..                  ...  ...
360                 231   50
361                 226   50
362                 155   50
363                 144   50
364                 172   50

[365 rows x 2 columns]

In [11]:
df1=pd.read_csv("/content/Student.csv")
df1

     Maths  Physics  Chemistry  Result
0       17       27         22       0
1       72       82         77       1
2       97       18         13       0
3        8       42         37       0
4       32       25         20       0
..     ...      ...        ...     ...
995      4       48         64       0
996     63       22         88       0
997     90       64         43       1
998     67       41          6       0
999     92       74          9       0

[1000 rows x 4 columns]

In [12]:
print("Average mark of student \n",df1.mean())

Average mark of student
 Maths        50.842
Physics      52.316
Chemistry    52.239
Result        0.245
dtype: float64

In [13]:
df1['Total_Score'] = df1['Maths'] + df1['Physics'] + df1['Chemistry']
top_10 = df1.sort_values(by='Total_Score', ascending=False).head(10)
print(top_10)
print("\n" + "="*40 + "\n")

     Maths  Physics  Chemistry  Result  Total_Score
21      98       85         97       1          280
407    100       83         97       1          280
779     91       88         98       1          277
103     99       80         95       1          274
713     95       90         88       1          273
521     85       93         92       1          270
787     93       88         85       1          266
86      95       72         99       1          266
853     98       67         99       1          264
212     89       93         82       1          264

========================================

In [14]:
highest_scores = df1[['Maths', 'Physics', 'Chemistry']].max()
print(highest_scores)
print("\n" + "="*40 + "\n")

Maths        100
Physics       95
Chemistry     99
dtype: int64

========================================

In [15]:
def assign_grade(score):
    if score >= 80:
        return 'A'
    elif score >= 60:
        return 'B'
    elif score >= 40:
        return 'C'
    else:
        return 'D'

df1['Average_Score'] = df1['Total_Score'] / 3
df1['Grade'] = df1['Average_Score'].apply(assign_grade)
print(df1[['Maths', 'Physics', 'Chemistry', 'Total_Score', 'Average_Score', 'Grade']].head())
print("\nGRADE DISTRIBUTION COUNTS:")
print(df1['Grade'].value_counts())
print("\n" + "="*40 + "\n")

   Maths  Physics  Chemistry  Total_Score  Average_Score Grade
0     17       27         22           66      22.000000     D
1     72       82         77          231      77.000000     B
2     97       18         13          128      42.666667     C
3      8       42         37           87      29.000000     D
4     32       25         20           77      25.666667     D

GRADE DISTRIBUTION COUNTS:
Grade
C    473
B    263
D    229
A     35
Name: count, dtype: int64

========================================

In [16]:
summary_stats = df1[['Maths', 'Physics', 'Chemistry', 'Total_Score', 'Average_Score']].describe()
print(summary_stats)

             Maths      Physics    Chemistry  Total_Score  Average_Score
count  1000.000000  1000.000000  1000.000000  1000.000000    1000.000000
mean     50.842000    52.316000    52.239000   155.397000      51.799000
std      29.238775    24.801114    27.397052    46.271616      15.423872
min       0.000000    10.000000     5.000000    30.000000      10.000000
25%      26.000000    31.000000    29.750000   123.750000      41.250000
50%      51.000000    51.000000    53.000000   156.000000      52.000000
75%      76.000000    74.000000    76.000000   188.000000      62.666667
max     100.000000    95.000000    99.000000   280.000000      93.333333

In [17]:
df2=pd.read_csv("/content/employee_salary_dataset.csv")
df2

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [18]:

dept_avg_salary = df2.groupby('Department')['Monthly_Salary'].mean().reset_index()
print(dept_avg_salary)



highest_paid = df2.loc[df2['Monthly_Salary'].idxmax()]
lowest_paid = df2.loc[df2['Monthly_Salary'].idxmin()]

print("Highest Paid:")
print(highest_paid[['EmployeeID', 'Name', 'Department', 'Monthly_Salary']])
print("\nLowest Paid:")
print(lowest_paid[['EmployeeID', 'Name', 'Department', 'Monthly_Salary']])

gender_salary_stats = df2.groupby('Gender')['Monthly_Salary'].agg(['mean', 'median', 'min', 'max']).reset_index()
print(gender_salary_stats)

print("Average Salary by Education Level:")
edu_trend = df2.groupby('Education_Level')['Monthly_Salary'].mean().sort_values(ascending=False).reset_index()
print(edu_trend)

correlation_exp = df2['Experience_Years'].corr(df2['Monthly_Salary'])
correlation_age = df2['Age'].corr(df2['Monthly_Salary'])
print(f"\nCorrelation between Experience and Salary: {correlation_exp:.2f}")
print(f"Correlation between Age and Salary: {correlation_age:.2f}")

salary_report = df2.groupby(['City', 'Department'])['Monthly_Salary'].describe()
print(salary_report)

   Department  Monthly_Salary
0     Finance    67261.900000
1          HR    82945.142857
2          IT    76520.500000
3   Marketing    96430.846154
4  Operations    84239.900000
Highest Paid:
EmployeeID                 38
Name              Employee_38
Department         Operations
Monthly_Salary         149123
Name: 37, dtype: object

Lowest Paid:
EmployeeID                 49
Name              Employee_49
Department            Finance
Monthly_Salary          28420
Name: 48, dtype: object
   Gender          mean   median    min     max
0  Female  87306.185185  88208.0  28420  134616
1    Male  76398.826087  65818.0  28436  149123
Average Salary by Education Level:
  Education_Level  Monthly_Salary
0          Master    86258.210526
1     High School    83676.416667
2        Bachelor    82441.777778
3             PhD    72944.100000

Correlation between Experience and Salary: 0.07
Correlation between Age and Salary: 0.06
                      count           mean           std       min        25%  \
City      Department
Bangalore HR            2.0   98622.500000  47846.380349   64790.0   81706.25
          IT            2.0   87906.500000  60919.370520   44830.0   66368.25
          Marketing     6.0  103452.666667  26828.825794   65764.0   82780.00
          Operations    1.0   95271.000000           NaN   95271.0   95271.00
Chennai   HR            2.0   58479.000000   3865.045666   55746.0   57112.50
          IT            1.0   81491.000000           NaN   81491.0   81491.00
          Operations    2.0   44224.500000    726.198664   43711.0   43967.75
Delhi     Finance       5.0   63903.200000  26482.336749   28436.0   57635.00
          HR            1.0  134616.000000           NaN  134616.0  134616.00
          IT            1.0  119660.000000           NaN  119660.0  119660.00
          Marketing     4.0  105216.250000  30137.239615   68525.0   91788.50
          Operations    4.0  101332.500000  22440.202888   79045.0   91079.50
Hyderabad Finance       3.0   72933.666667  44883.972889   28420.0   50311.00
          HR            1.0   88208.000000           NaN   88208.0   88208.00
          IT            5.0   63543.200000  28827.473367   30600.0   42429.00
          Marketing     2.0   56365.000000  36020.019434   30895.0   43630.00
          Operations    1.0   72333.000000           NaN   72333.0   72333.00
Mumbai    Finance       2.0   67151.000000   1885.146679   65818.0   66484.50
          HR            1.0   43589.000000           NaN   43589.0   43589.00
          IT            1.0   70525.000000           NaN   70525.0   70525.00
          Marketing     1.0   99290.000000           NaN   99290.0   99290.00
          Operations    2.0   90508.000000  82894.127958   31893.0   61200.50

                           50%        75%       max
City      Department
Bangalore HR           98622.5  115538.75  132455.0
          IT           87906.5  109444.75  130983.0
          Marketing   114870.5  122604.00  127946.0
          Operations   95271.0   95271.00   95271.0
Chennai   HR           58479.0   59845.50   61212.0
          IT           81491.0   81491.00   81491.0
          Operations   44224.5   44481.25   44738.0
Delhi     Finance      58828.0   73404.00  101213.0
          HR          134616.0  134616.00  134616.0
          IT          119660.0  119660.00  119660.0
          Marketing   105479.5  118907.25  141381.0
          Operations   96917.5  107170.50  132450.0
Hyderabad Finance      72202.0   95190.50  118179.0
          HR           88208.0   88208.00   88208.0
          IT           69064.0   70714.00  104909.0
          Marketing    56365.0   69100.00   81835.0
          Operations   72333.0   72333.00   72333.0
Mumbai    Finance      67151.0   67817.50   68484.0
          HR           43589.0   43589.00   43589.0
          IT           70525.0   70525.00   70525.0
          Marketing    99290.0   99290.00   99290.0
          Operations   90508.0  119815.50  149123.0

In [19]:
df2

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752